### ISSUE TITLE
运行出现了错误

### ISSUE THREAD

**Issue by r1ghrfhd** [1oid/remotejs#1]
curl -X POST http://127.0.0.1:9999/remote -d "eval=getQueryString(\"1\")"
{"error":"Can only perform operation while paused. (-32000)"}

**Comment by 1oid** [comment]
方便发站点吗，不方便的话，主要的函数代码块，我本地复测下

**Comment by 1oid** [comment]
另外有一个事情你需要注意，你这个getQueryString里面的"1"引号会和外面的闭合，注意下这个语法

**Comment by r1ghrfhd** [comment]
非常感谢 找到了原因  是自己操作问题 。 经过手工cdp调试发现取ws地址的时候 我要取json里面的第二个地址。跟着对比浏览器开启了2个web页面 ，在调试的时候2个web界面都有debug断点 估计是这个原因引起的。
